# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: pollschain.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" 
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  #
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.pollschain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
