# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  Vnet:

services:
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=test
      - COUCHDB_PASSWORD=test
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - Vnet

  peer0.org1.pollschain.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=test
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=test
      - CORE_PEER_ID=peer0.org1.pollschain.com
      - CORE_PEER_ADDRESS=peer0.org1.pollschain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.pollschain.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.pollschain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    depends_on:
      - couchdb0

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=test
      - COUCHDB_PASSWORD=test
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    networks:
      - Vnet

  peer1.org1.pollschain.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=test
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=test
      - CORE_PEER_ID=peer1.org1.pollschain.com
      - CORE_PEER_ADDRESS=peer1.org1.pollschain.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.pollschain.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.pollschain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    depends_on:
      - couchdb1
